#!/bin/sh

# this takes files generated by graph_get_cam_connectivity.sh and turns
# them into sparse matrices in matrix market format. note that the camera
# ids are lost

if [ $# -ne 1 ]; then
	>&2 echo 'error: use ./cconn_to_matrixmarket.sh <camera connectivity graph file>'
	exit
fi

gawk 'BEGIN {
		num_cameras = 0;
		nnz = 0;
	}
	{
		if($1 == "CAM")
			cameras[$2] = ++ num_cameras;
		# keep a list of camera index mapping from graph to one-based indices

		if($1 == "EDGE")
			edges[++ nnz] = cameras[$3] " " cameras[$2] " " $4; # note that mtx i supposed to contain the *lower* triangular portion
		# keep a list of edges, already converted to strings, index by integer so that the order is not lost
	}
	END {
		print "%%MatrixMarket matrix coordinate real symmetric";
		print "%";
		print "% indirect camera incidence graph";
		print "%";
		print num_cameras " " num_cameras " " nnz;
		for(i = 1; i <= nnz; ++ i)
			print edges[i];
	}' $1
